"""initial schema — full datamodel.md §3–§7 (Phase 2 baseline)

Revision ID: 0001
Revises:
Create Date: 2026-05-11

Implements `docs/datamodel.md` end-to-end:
  §3 GeographicArea
  §4 SchoolDistrict, School, AttendanceZone
  §5 Parcel, Listing, Sale (materialized view)
  §6 MarketSnapshot (incl. §6a phase columns)
  §6b MarketSignal
  §7 DataSource, SourceFetch

Hand-written rather than autogenerated because Alembic's autogenerate cannot
see PostGIS column types, materialized views, EXCLUDE constraints, or
expression indexes. Where SQLAlchemy can't express a piece (e.g. the
`UNIQUE (..., (payload->>'dedupe_key'), (computed_at::date))` index on
`market_signal`), it lives here as raw `op.execute(...)`.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ── Enum surfaces (mirror apps/api/src/bayre_api/models/base.py) ───────────
GEO_KIND = (
    "metro",
    "county",
    "city",
    "neighborhood",
    "zip",
    "school_zone",
    "school_district",
    "custom_polygon",
)
SCHOOL_LEVEL = ("elementary", "middle", "high", "k12")
LISTING_STATUS = ("active", "pending", "sold", "withdrawn", "expired", "unknown")
PROPERTY_TYPE = ("sfh", "condo", "townhome", "multifamily", "land", "mobile", "other")
PERIOD_KIND = ("weekly", "monthly", "quarterly", "yearly")
MARKET_PHASE = ("peak", "cooling", "trough", "recovery", "unknown")
SIGNAL_KIND = (
    "phase_transition",
    "mos_threshold",
    "s2l_threshold",
    "dom_threshold",
    "inventory_spike",
    "price_drop_pct",
    "rate_threshold",
    "new_listing",
    "price_change",
    "status_flip",
    "sold",
)


def upgrade() -> None:
    # ── Extensions ─────────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")  # for the EXCLUDE on attendance_zone

    # ── Enums ──────────────────────────────────────────────────────────────
    op.execute(f"CREATE TYPE geo_kind AS ENUM ({_enum_values(GEO_KIND)});")
    op.execute(f"CREATE TYPE school_level AS ENUM ({_enum_values(SCHOOL_LEVEL)});")
    op.execute(f"CREATE TYPE listing_status AS ENUM ({_enum_values(LISTING_STATUS)});")
    op.execute(f"CREATE TYPE property_type AS ENUM ({_enum_values(PROPERTY_TYPE)});")
    op.execute(f"CREATE TYPE period_kind AS ENUM ({_enum_values(PERIOD_KIND)});")
    op.execute(f"CREATE TYPE market_phase AS ENUM ({_enum_values(MARKET_PHASE)});")
    op.execute(f"CREATE TYPE signal_kind AS ENUM ({_enum_values(SIGNAL_KIND)});")

    # ── geographic_area ────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE geographic_area (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          kind            geo_kind NOT NULL,
          name            TEXT NOT NULL,
          slug            TEXT NOT NULL,
          parent_id       UUID REFERENCES geographic_area(id),
          metro_id        UUID REFERENCES geographic_area(id),
          geometry        geometry(MultiPolygon, 4326),
          centroid        geometry(Point, 4326)
                          GENERATED ALWAYS AS (ST_Centroid(geometry)) STORED,
          area_sqkm       NUMERIC
                          GENERATED ALWAYS AS (ST_Area(geometry::geography) / 1e6) STORED,
          population      INTEGER,
          median_household_income NUMERIC,
          metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
          source          TEXT,
          effective_from  DATE,
          effective_to    DATE,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (kind, parent_id, slug)
        );
        """
    )
    # NOTE: `geometry` is documented as NOT NULL in datamodel.md §3.1, but the
    # initial Phase 2 seed (revision 0002) inserts the 18 priority rows with
    # geometry left NULL — boundary ingest is a downstream ETL job. A later
    # migration will add `ALTER TABLE geographic_area ALTER COLUMN geometry SET NOT NULL`
    # once boundaries land.

    op.execute("CREATE INDEX idx_geo_geom ON geographic_area USING GIST (geometry);")
    op.execute("CREATE INDEX idx_geo_centroid ON geographic_area USING GIST (centroid);")
    op.execute("CREATE INDEX idx_geo_kind_metro ON geographic_area (metro_id, kind);")
    op.execute("CREATE INDEX idx_geo_parent ON geographic_area (parent_id);")
    op.execute("CREATE INDEX idx_geo_slug ON geographic_area (slug);")

    # ── school_district ────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE school_district (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          cds_code        TEXT UNIQUE,
          name            TEXT NOT NULL,
          area_id         UUID NOT NULL REFERENCES geographic_area(id),
          total_enrollment INTEGER,
          per_pupil_spending NUMERIC,
          metadata        JSONB NOT NULL DEFAULT '{}'::jsonb
        );
        """
    )

    # ── school ─────────────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE school (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          district_id     UUID NOT NULL REFERENCES school_district(id),
          cds_code        TEXT UNIQUE,
          name            TEXT NOT NULL,
          level           school_level NOT NULL,
          grades          INT4RANGE,
          address         TEXT,
          location        geometry(Point, 4326),
          enrollment      INTEGER,
          student_teacher_ratio NUMERIC,
          ratings         JSONB NOT NULL DEFAULT '{}'::jsonb,
          data_quality_score SMALLINT,
          feeder_pattern  JSONB,
          updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )
    op.execute("CREATE INDEX idx_school_district ON school (district_id);")
    op.execute("CREATE INDEX idx_school_loc ON school USING GIST (location);")

    # ── attendance_zone ────────────────────────────────────────────────────
    # The EXCLUDE constraint prevents two overlapping current zones for the
    # same school — protects against bad ingest data. Requires btree_gist.
    op.execute(
        """
        CREATE TABLE attendance_zone (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          school_id       UUID NOT NULL REFERENCES school(id),
          area_id         UUID NOT NULL REFERENCES geographic_area(id),
          effective_from  DATE NOT NULL,
          effective_to    DATE,
          source_url      TEXT,
          source_doc      TEXT,
          notes           TEXT,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
          EXCLUDE USING GIST (
            school_id WITH =,
            daterange(effective_from, COALESCE(effective_to, 'infinity'::date), '[)') WITH &&
          )
        );
        """
    )

    # ── parcel ─────────────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE parcel (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          apn             TEXT NOT NULL,
          county_id       UUID NOT NULL REFERENCES geographic_area(id),
          address         TEXT,
          location        geometry(Point, 4326) NOT NULL,
          lot_sqft        INTEGER,
          zoning          TEXT,
          city_id         UUID REFERENCES geographic_area(id),
          neighborhood_id UUID REFERENCES geographic_area(id),
          base_assessed_value NUMERIC,
          base_year       INTEGER,
          current_tax_rate NUMERIC,
          mello_roos      JSONB,
          hoa             JSONB,
          ada_features    JSONB,
          raw_assessor    JSONB,
          source          TEXT,
          updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (county_id, apn)
        );
        """
    )
    op.execute("CREATE INDEX idx_parcel_loc ON parcel USING GIST (location);")
    op.execute("CREATE INDEX idx_parcel_city ON parcel (city_id);")
    op.execute("CREATE INDEX idx_parcel_neighborhood ON parcel (neighborhood_id);")

    # ── listing ────────────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE listing (
          id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          parcel_id         UUID REFERENCES parcel(id),
          source            TEXT NOT NULL,
          source_listing_id TEXT NOT NULL,
          status            listing_status NOT NULL,
          property_type     property_type NOT NULL,
          list_price        NUMERIC,
          sold_price        NUMERIC,
          list_date         DATE,
          pending_date      DATE,
          sold_date         DATE,
          off_market_date   DATE,
          beds              SMALLINT,
          baths             NUMERIC,
          sqft              INTEGER,
          year_built        SMALLINT,
          days_on_market    INTEGER,
          price_drops       JSONB,
          raw_payload       JSONB,
          fetched_at        TIMESTAMPTZ NOT NULL,
          UNIQUE (source, source_listing_id)
        );
        """
    )
    op.execute("CREATE INDEX idx_listing_parcel ON listing (parcel_id);")
    op.execute("CREATE INDEX idx_listing_status_sold ON listing (sold_date) WHERE status = 'sold';")
    op.execute("CREATE INDEX idx_listing_active ON listing (status) WHERE status = 'active';")

    # ── sale (materialized view) ───────────────────────────────────────────
    op.execute(
        """
        CREATE MATERIALIZED VIEW sale AS
        SELECT
          l.id AS listing_id,
          l.parcel_id,
          l.sold_date,
          l.sold_price,
          l.list_price,
          l.sold_price / NULLIF(l.list_price, 0) AS sale_to_list,
          l.days_on_market,
          l.property_type,
          l.beds, l.baths, l.sqft,
          l.sold_price / NULLIF(l.sqft, 0) AS price_per_sqft,
          p.city_id, p.neighborhood_id, p.county_id, p.location
        FROM listing l
        LEFT JOIN parcel p ON p.id = l.parcel_id
        WHERE l.status = 'sold' AND l.sold_date IS NOT NULL
        WITH NO DATA;
        """
    )
    op.execute("CREATE UNIQUE INDEX idx_sale_listing ON sale (listing_id);")
    op.execute("CREATE INDEX idx_sale_date ON sale (sold_date);")
    op.execute("CREATE INDEX idx_sale_city_date ON sale (city_id, sold_date);")
    op.execute("CREATE INDEX idx_sale_loc ON sale USING GIST (location);")

    # ── market_snapshot (with §6a phase columns inline) ────────────────────
    op.execute(
        """
        CREATE TABLE market_snapshot (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          area_id         UUID NOT NULL REFERENCES geographic_area(id),
          property_type   property_type NOT NULL,
          period_kind     period_kind NOT NULL,
          period_start    DATE NOT NULL,
          period_end      DATE NOT NULL,

          median_sale_price       NUMERIC,
          median_list_price       NUMERIC,
          median_ppsf             NUMERIC,
          sale_to_list_ratio      NUMERIC,
          pct_sold_over_asking    NUMERIC,
          median_dom              INTEGER,
          homes_sold              INTEGER,
          active_listings         INTEGER,
          new_listings            INTEGER,
          pending_sales           INTEGER,
          months_of_supply        NUMERIC,
          pct_with_price_drops    NUMERIC,
          median_drop_pct         NUMERIC,
          median_size_sqft        INTEGER,
          median_year_built       SMALLINT,

          by_bedrooms     JSONB,
          percentiles     JSONB,

          sample_size       INTEGER NOT NULL,
          confidence_score  SMALLINT NOT NULL,
          source_versions   JSONB NOT NULL,
          computed_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

          phase             market_phase,
          clock_position    NUMERIC,
          buyer_pressure    SMALLINT,
          seller_pressure   SMALLINT,
          phase_components  JSONB,

          UNIQUE (area_id, property_type, period_kind, period_start)
        );
        """
    )
    op.execute(
        """
        CREATE INDEX idx_snapshot_lookup
          ON market_snapshot (area_id, property_type, period_kind, period_start DESC);
        """
    )
    op.execute(
        """
        CREATE INDEX idx_snapshot_timeseries
          ON market_snapshot (area_id, property_type, period_kind, period_start);
        """
    )

    op.execute(
        """
        CREATE VIEW current_market_phase AS
        SELECT DISTINCT ON (area_id, property_type)
          area_id, property_type, period_start,
          phase, clock_position, buyer_pressure, seller_pressure, phase_components,
          confidence_score
        FROM market_snapshot
        WHERE period_kind = 'weekly'
        ORDER BY area_id, property_type, period_start DESC;
        """
    )

    # ── market_signal ──────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE market_signal (
          id              BIGSERIAL PRIMARY KEY,
          area_id         UUID NOT NULL REFERENCES geographic_area(id),
          property_type   property_type,
          kind            signal_kind NOT NULL,
          severity        SMALLINT NOT NULL,
          payload         JSONB NOT NULL,
          source_snapshot_ids UUID[] NOT NULL,
          source_fetch_ids    UUID[],
          computed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
          source_listing_id UUID REFERENCES listing(id)
        );
        """
    )
    op.execute("CREATE INDEX idx_signal_area_time ON market_signal (area_id, computed_at DESC);")
    op.execute("CREATE INDEX idx_signal_seq ON market_signal (id);")
    op.execute("CREATE INDEX idx_signal_kind_time ON market_signal (kind, computed_at DESC);")
    # Idempotency dedupe — expression index, can't be expressed via SQLAlchemy.
    op.execute(
        """
        CREATE UNIQUE INDEX idx_signal_dedupe
          ON market_signal (area_id, kind, (payload->>'dedupe_key'), ((computed_at)::date));
        """
    )

    # ── data_source ────────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE data_source (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          name            TEXT UNIQUE NOT NULL,
          display_name    TEXT NOT NULL,
          attribution     TEXT NOT NULL,
          license         TEXT NOT NULL,
          base_url        TEXT,
          reliability     JSONB NOT NULL,
          is_active       BOOLEAN NOT NULL DEFAULT true,
          added_at        DATE NOT NULL,
          notes           TEXT
        );
        """
    )

    # ── source_fetch ───────────────────────────────────────────────────────
    op.execute(
        """
        CREATE TABLE source_fetch (
          id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          source_id       UUID NOT NULL REFERENCES data_source(id),
          area_id         UUID REFERENCES geographic_area(id),
          fetched_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
          status          TEXT NOT NULL,
          http_status     INTEGER,
          payload_uri     TEXT,
          payload_bytes   INTEGER,
          rows_parsed     INTEGER,
          parse_anomalies JSONB,
          duration_ms     INTEGER,
          error           TEXT
        );
        """
    )
    op.execute("CREATE INDEX idx_fetch_source_time ON source_fetch (source_id, fetched_at DESC);")
    op.execute("CREATE INDEX idx_fetch_area_time ON source_fetch (area_id, fetched_at DESC);")


def downgrade() -> None:
    # Reverse order — children first.
    op.execute("DROP TABLE IF EXISTS source_fetch;")
    op.execute("DROP TABLE IF EXISTS data_source;")
    op.execute("DROP INDEX IF EXISTS idx_signal_dedupe;")
    op.execute("DROP TABLE IF EXISTS market_signal;")
    op.execute("DROP VIEW  IF EXISTS current_market_phase;")
    op.execute("DROP TABLE IF EXISTS market_snapshot;")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS sale;")
    op.execute("DROP TABLE IF EXISTS listing;")
    op.execute("DROP TABLE IF EXISTS parcel;")
    op.execute("DROP TABLE IF EXISTS attendance_zone;")
    op.execute("DROP TABLE IF EXISTS school;")
    op.execute("DROP TABLE IF EXISTS school_district;")
    op.execute("DROP TABLE IF EXISTS geographic_area;")

    # Enums.
    for type_name in (
        "signal_kind",
        "market_phase",
        "period_kind",
        "property_type",
        "listing_status",
        "school_level",
        "geo_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {type_name};")
    # Leave extensions in place — other databases on the same Neon project
    # may rely on them, and dropping them is destructive.


# ── helpers ────────────────────────────────────────────────────────────────


def _enum_values(values: tuple[str, ...]) -> str:
    """Quote enum literals for a CREATE TYPE statement."""
    return ", ".join(f"'{v}'" for v in values)


# Silence flake8 for `sa` / `postgresql` imports kept for downstream migrations.
_ = (sa, postgresql)
